// Builds one static package per target into dist/<target>/.
// Usage: node tools/build.mjs [target ...]   (default: all targets)
import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { existsSync, realpathSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));

const SAFE_NAME = /^[a-z0-9-]+$/;
const SKIPPED_FILES = new Set(['.gitkeep', '.DS_Store']);

export async function loadTargets(root = ROOT) {
  return JSON.parse(await readFile(join(root, 'config', 'targets.json'), 'utf8'));
}

export function renderConfig(config) {
  return `// Generated by tools/build.mjs. Do not edit.\nexport const config = ${JSON.stringify(config, null, 2)};\n`;
}

export async function buildTarget(name, target, { root = ROOT, outDir = join(root, 'dist') } = {}) {
  if (!SAFE_NAME.test(name)) throw new Error(`Invalid target name: "${name}"`);
  const runtime = target.runtime ?? {};
  const theme = runtime.theme;
  if (typeof theme !== 'string' || !SAFE_NAME.test(theme)) {
    throw new Error(`Target "${name}": invalid theme "${theme}"`);
  }
  const themeDir = join(root, 'themes', theme);
  if (!existsSync(themeDir)) throw new Error(`Target "${name}": theme folder themes/${theme} not found`);

  // Only the target's own ads adapter goes into the package.
  const adsDir = join(root, 'src', 'ads');
  const adapter = runtime.ads?.adapter ?? 'none';
  if (!SAFE_NAME.test(adapter) || !existsSync(join(adsDir, `${adapter}.js`))) {
    throw new Error(`Target "${name}": ads adapter "${adapter}" not found in src/ads`);
  }
  const shippedAds = new Set(['index.js', `${adapter}.js`]);

  const dest = join(outDir, name);
  await rm(dest, { recursive: true, force: true });
  await mkdir(dest, { recursive: true });

  const filter = (src) => {
    if (SKIPPED_FILES.has(basename(src))) return false;
    return dirname(src) !== adsDir || shippedAds.has(basename(src));
  };
  // Symlinks are copied as the files they point to: a link would point back
  // into this machine's source tree and escape the size and URL checks.
  await cp(join(root, 'index.html'), join(dest, 'index.html'), { dereference: true });
  await cp(join(root, 'src'), join(dest, 'src'), { recursive: true, filter, dereference: true });
  await cp(themeDir, join(dest, 'themes', theme), { recursive: true, filter, dereference: true });

  // Replaces the development config copied from src/.
  await writeFile(join(dest, 'src', 'config.js'), renderConfig({ target: name, ...runtime }));
  return dest;
}

export async function build({ root = ROOT, outDir = join(root, 'dist'), names = [] } = {}) {
  const targets = await loadTargets(root);
  const selected = names.length > 0 ? names : Object.keys(targets);
  const built = [];
  for (const name of selected) {
    if (!Object.hasOwn(targets, name)) throw new Error(`Unknown target: "${name}"`);
    built.push(await buildTarget(name, targets[name], { root, outDir }));
  }
  return built;
}

// Run as a command, also when called through a symlinked path.
if (process.argv[1] && import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href) {
  try {
    for (const dir of await build({ names: process.argv.slice(2) })) {
      console.log(`built ${dir}`);
    }
  } catch (error) {
    console.error(`build failed: ${error.message}`);
    process.exit(1);
  }
}
