// Texts of the prototype in German and English.

export const TEXTS = {
  de: {
    title: 'Full Roast Ahead – Prototyp',
    perMinute: '{value} pro Minute',
    sound: 'Ton an oder aus',
    language: 'English',
    restart: 'Neu starten',
    restartConfirm: 'Den Prototyp von vorn beginnen?',
    goal: 'Ziel',
    goalDone: 'Geschafft!',
    reward: '+{value}',
    shop: 'Ausbau',
    buy: 'Kaufen',
    soon: 'Als Nächstes: {name}',
    noItems: 'Verkaufe deinen ersten Kaffee, dann kannst du ausbauen.',
    allBought: 'Alles gekauft. Mehr gibt es in diesem Prototyp nicht.',
    lockSale: 'Nach deinem ersten Verkauf',
    lockAfter: 'Nach: {name}',
    stats: {
      title: 'Deine Rösterei',
      cart: 'Im Wagen',
      cartValue: '{count} / {capacity} Säcke',
      guests: 'Gäste',
      guestsValue: 'alle {seconds} s',
      price: 'Preis pro Sack',
      priceValue: '{base} (Wunsch: {matched})',
      lost: 'Gäste gegangen',
    },
    stir: 'Rühren',
    load: 'Rösten',
    eject: 'Auswerfen',
    pan: 'Röstpfanne',
    wish: 'Wunsch am Wagen: {level}',
    wishNone: 'Gerade wartet niemand am Wagen.',
    levels: { light: 'hell', medium: 'mittel', dark: 'dunkel' },
    status: {
      empty: 'Tippe auf die Pfanne, um eine Charge zu rösten.',
      emptyAuto: 'Die Helferin füllt gleich nach.',
      drying: 'Die Bohnen trocknen … warte auf den ersten Crack.',
      crack: 'Erster Crack! Jetzt kannst du auswerfen.',
      roast: 'Röstgrad: {level}',
      cooling: 'Die Bohnen kühlen ab.',
      waiting: 'Der Wagen ist voll. Die Charge wartet.',
    },
    auto: {
      helper: 'Die Helferin wirft bei „mittel“ aus.',
      profile: 'Das Röstprofil folgt den Wünschen der Gäste.',
    },
    items: {
      biggerPan: { name: 'Größere Pfanne', effect: '2 Säcke pro Charge' },
      sign: { name: 'Aushängeschild', effect: 'Mehr Gäste kommen vorbei' },
      helper: { name: 'Helferin', effect: 'Röstet von selbst, wirft bei „mittel“ aus' },
      drum: { name: 'Trommelröster', effect: 'Röstet 3 Säcke pro Charge von selbst' },
      profile: { name: 'Röstprofil', effect: 'Maschinen rösten, was die Gäste wünschen' },
      cafe: { name: 'Café', effect: 'Mehr Gäste, höhere Preise, 12 Plätze im Wagen' },
    },
    goals: {
      stir: 'Tippe auf die Pfanne, um zu rösten.',
      eject: 'Warte auf den ersten Crack, dann: Auswerfen.',
      sell: 'Verkaufe deinen ersten Kaffee am Wagen.',
      biggerPan: 'Kaufe eine größere Pfanne.',
      match: 'Triff einen Wunsch genau: Achte auf die Sprechblase.',
      sign: 'Häng ein Schild auf, damit mehr Gäste kommen.',
      helper: 'Stell eine Helferin ein.',
      drum: 'Kauf deinen ersten Trommelröster.',
      profile: 'Kauf ein Röstprofil.',
      cafe: 'Eröffne das Café.',
    },
    floaters: {
      perfect: 'Perfekt!',
      firstCrack: 'Erster Crack!',
      secondCrack: 'Zweiter Crack!',
      full: 'Wagen voll!',
      leaving: 'Gäste gehen!',
      delivery: 'Sonderlieferung! Antippen',
      caught: 'Sonderlieferung +{value}',
    },
    banners: {
      helper: 'Deine Helferin ist da!',
      drum: 'Ein Trommelröster!',
      cafe: 'Das Café ist eröffnet!',
      sign: 'Das Schild hängt!',
    },
    end: {
      title: 'Das war der Prototyp',
      body: 'Das sind die ersten fünf Minuten. Du kannst weiterspielen, aber es kommt nichts Neues mehr. Wie hat es sich angefühlt?',
      close: 'Weiterspielen',
    },
  },
  en: {
    title: 'Full Roast Ahead – prototype',
    perMinute: '{value} per minute',
    sound: 'Sound on or off',
    language: 'Deutsch',
    restart: 'Start over',
    restartConfirm: 'Start the prototype from the beginning?',
    goal: 'Goal',
    goalDone: 'Done!',
    reward: '+{value}',
    shop: 'Upgrades',
    buy: 'Buy',
    soon: 'Next: {name}',
    noItems: 'Sell your first coffee, then you can expand.',
    allBought: 'All bought. There is nothing more in this prototype.',
    lockSale: 'After your first sale',
    lockAfter: 'After: {name}',
    stats: {
      title: 'Your roastery',
      cart: 'On the cart',
      cartValue: '{count} / {capacity} bags',
      guests: 'Guests',
      guestsValue: 'every {seconds} s',
      price: 'Price per bag',
      priceValue: '{base} (wish: {matched})',
      lost: 'Guests who left',
    },
    stir: 'Stir',
    load: 'Roast',
    eject: 'Eject',
    pan: 'Roasting pan',
    wish: 'Wish at the cart: {level}',
    wishNone: 'Nobody is waiting at the cart.',
    levels: { light: 'light', medium: 'medium', dark: 'dark' },
    status: {
      empty: 'Tap the pan to roast a batch.',
      emptyAuto: 'Your helper refills it in a moment.',
      drying: 'The beans are drying … wait for the first crack.',
      crack: 'First crack! You can eject now.',
      roast: 'Roast: {level}',
      cooling: 'The beans are cooling.',
      waiting: 'The cart is full. The batch waits.',
    },
    auto: {
      helper: 'Your helper ejects at "medium".',
      profile: "The roast profile follows the guests' wishes.",
    },
    items: {
      biggerPan: { name: 'Bigger pan', effect: '2 bags per batch' },
      sign: { name: 'Hanging sign', effect: 'More guests stop by' },
      helper: { name: 'Helper', effect: 'Roasts on her own, ejects at "medium"' },
      drum: { name: 'Drum roaster', effect: 'Roasts 3 bags per batch on its own' },
      profile: { name: 'Roast profile', effect: 'Machines roast what guests wish for' },
      cafe: { name: 'Café', effect: 'More guests, higher prices, 12 spaces on the cart' },
    },
    goals: {
      stir: 'Tap the pan to start roasting.',
      eject: 'Wait for the first crack, then eject.',
      sell: 'Sell your first coffee at the cart.',
      biggerPan: 'Buy a bigger pan.',
      match: "Match a guest's wish exactly: watch the speech bubble.",
      sign: 'Put up a sign so more guests come.',
      helper: 'Hire a helper.',
      drum: 'Buy your first drum roaster.',
      profile: 'Buy a roast profile.',
      cafe: 'Open the café.',
    },
    floaters: {
      perfect: 'Perfect!',
      firstCrack: 'First crack!',
      secondCrack: 'Second crack!',
      full: 'Cart full!',
      leaving: 'Guests leaving!',
      delivery: 'Special delivery! Tap it',
      caught: 'Special delivery +{value}',
    },
    banners: {
      helper: 'Your helper is here!',
      drum: 'A drum roaster!',
      cafe: 'The café is open!',
      sign: 'The sign is up!',
    },
    end: {
      title: 'That was the prototype',
      body: 'These are the first five minutes. You can keep playing, but nothing new comes after this. How did it feel?',
      close: 'Keep playing',
    },
  },
};

export function format(template, values = {}) {
  return template.replace(/\{(\w+)\}/g, (match, key) => (key in values ? String(values[key]) : match));
}
